
#ifndef CODELITHIC_SITE_DEFINE_H
#define CODELITHIC_SITE_DEFINE_H

#define _ID "_id"
#define _ACTIVITYNAME "_activityName"
#define USER_DEFINITION "USER_DEFINITION"
#define USER_LOGGED "USER_LOGGED"
#define USER_NOT_LOGGED "USER_NOT_LOGGED"
#define USER_AVATAR "USER_AVATAR"

#endif /* CODELITHIC_SITE_DEFINE_H */
